### ISSUE TITLE
Make the UpdateShop method require a DataGridView object

### ISSUE THREAD

**Issue by ThatFrostyy** [ThatFrostyy/Survival#1]
Currently the shop does not work because we are not using the same object of the `shopGrid` that is being updated.https://github.com/ThatFrostyy/Survival/blob/e2b46f1912dab331a63aecffc5af5ce750b4e2ea/Core.cs#L284-L285

**Comment by ohinson01** [comment]
Hi ThatFrostyy. 

This is my first time contributing to an open-source project and I came across this bug. I wanted to get some more experience working in C#. Mind if I take a stab at it? Does this have a time limit on when to complete?

**Comment by ThatFrostyy** [comment]
> Hi ThatFrostyy.
> 
> This is my first time contributing to an open-source project and I came across this bug. I wanted to get some more experience working in C#. Mind if I take a stab at it? Does this have a time limit on when to complete?

Yea man of course I apricate any help, and no there isn't any time limit.

**Comment by ThatFrostyy** [comment]
> I went ahead and looked at the code and ran the program. For this issue, did you want to convert the current setup to a DataGridView object? I am seeing that you do have columns and rows to show up when you scavenge for a rock, branch, apple, etc. Wanted clarification on what needs to be done. <img alt="image" width="217" src="https://private-user-images.githubusercontent.com/69820358/309412779-ac1f3f0d-c748-4bde-a8e5-762a4a6a2b26.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzNDc0OTMsIm5iZiI6MTcwOTM0NzE5MywicGF0aCI6Ii82OTgyMDM1OC8zMDk0MTI3NzktYWMxZjNmMGQtYzc0OC00YmRlLWE4ZTUtNzYyYTRhNmEyYjI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAyVDAyMzk1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhZTU4N2I5M2IzNDE4M2VjNDA5ZjE1MDVkZjQyOTgxMTVjNDg2MWQ2YjliZGU1MmEwMTA1N2JjZjU3Y2U4ODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UGXtQixSqhAxQ-bmWEii194OfmfZfVKNmaAmP3w8XWo">

Well the issue is when the player goes to the village and tries to do `shop` it does nothing, I think the issue arises due to the shop object not being passed. We should pass the dataGridView object which is the shop to the UpdateShop method so it can update the correct one. I hope I explained it well lol kinda new to issues on GitHub.

So one option is to have UpdateShop() take a object or initialize the object on game start then make that public and anything to do with the shop call it before continuing. That way there is only 1 shopGrid object that is used globally.

**Comment by ohinson01** [comment]
> > I went ahead and looked at the code and ran the program. For this issue, did you want to convert the current setup to a DataGridView object? I am seeing that you do have columns and rows to show up when you scavenge for a rock, branch, apple, etc. Wanted clarification on what needs to be done. <img alt="image" width="217" src="https://private-user-images.githubusercontent.com/69820358/309412779-ac1f3f0d-c748-4bde-a8e5-762a4a6a2b26.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzNDc0OTMsIm5iZiI6MTcwOTM0NzE5MywicGF0aCI6Ii82OTgyMDM1OC8zMDk0MTI3NzktYWMxZjNmMGQtYzc0OC00YmRlLWE4ZTUtNzYyYTRhNmEyYjI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAyVDAyMzk1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhZTU4N2I5M2IzNDE4M2VjNDA5ZjE1MDVkZjQyOTgxMTVjNDg2MWQ2YjliZGU1MmEwMTA1N2JjZjU3Y2U4ODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UGXtQixSqhAxQ-bmWEii194OfmfZfVKNmaAmP3w8XWo">
> 
> Well the issue is when the player goes to the village and tries to do `shop` it does nothing, I think the issue arises due to the shop object not being passed. We should pass the dataGridView object which is the shop to the UpdateShop method so it can update the correct one. I hope I explained it well lol kinda new to issues on GitHub.
> 
> So one option is to have UpdateShop() take a object or initialize the object on game start then make that public and anything to do with the shop call it before continuing. That way there is only 1 shopGrid object that is used globally.

Thanks for clarifying! No worries. I am also new to issues on GitHub, so this will be a first experience for me with helping out the open-source community. I will see what I can do. If you come up with a solution in the meantime, would love to hear how you went about it. Will give updates if I make any progress in resolving it.

**Comment by ThatFrostyy** [comment]
> > > I went ahead and looked at the code and ran the program. For this issue, did you want to convert the current setup to a DataGridView object? I am seeing that you do have columns and rows to show up when you scavenge for a rock, branch, apple, etc. Wanted clarification on what needs to be done. <img alt="image" width="217" src="https://private-user-images.githubusercontent.com/69820358/309412779-ac1f3f0d-c748-4bde-a8e5-762a4a6a2b26.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzNDc0OTMsIm5iZiI6MTcwOTM0NzE5MywicGF0aCI6Ii82OTgyMDM1OC8zMDk0MTI3NzktYWMxZjNmMGQtYzc0OC00YmRlLWE4ZTUtNzYyYTRhNmEyYjI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAyVDAyMzk1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhZTU4N2I5M2IzNDE4M2VjNDA5ZjE1MDVkZjQyOTgxMTVjNDg2MWQ2YjliZGU1MmEwMTA1N2JjZjU3Y2U4ODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UGXtQixSqhAxQ-bmWEii194OfmfZfVKNmaAmP3w8XWo">
> > 
> > 
> > Well the issue is when the player goes to the village and tries to do `shop` it does nothing, I think the issue arises due to the shop object not being passed. We should pass the dataGridView object which is the shop to the UpdateShop method so it can update the correct one. I hope I explained it well lol kinda new to issues on GitHub.
> > So one option is to have UpdateShop() take a object or initialize the object on game start then make that public and anything to do with the shop call it before continuing. That way there is only 1 shopGrid object that is used globally.
> 
> Thanks for clarifying! No worries. I am also new to issues on GitHub, so this will be a first experience for me with helping out the open-source community. I will see what I can do. If you come up with a solution in the meantime, would love to hear how you went about it. Will give updates if I make any progress in resolving it.

Thanks! good to hear I am right now working on combat and improving the inventory system but if I have any time I'll come on board to help you. For now I'll set you as the person working on this.

**Comment by ohinson01** [comment]
Question: How is the shop supposed to work? For instance, when a user types "shop", does it appear with already populated items in the grid or depending on the inventory of the user, do they sell items to the village? The UpdateShop() method seems like it updates the shop, but with what? 

Also, a separate grid for the shop should appear, correct? There is the inventory, so wondering if a user already has the inventory grid open, should the shop grid show below the inventory grid? Sorry for all these questions, but I was wondering what your intention with the shop should be for it to work,.

**Comment by ThatFrostyy** [comment]
> Question: How is the shop supposed to work? For instance, when a user types "shop", does it appear with already populated items in the grid or depending on the inventory of the user, do they sell items to the village? The UpdateShop() method seems like it updates the shop, but with what?
> 
> Also, a separate grid for the shop should appear, correct? There is the inventory, so wondering if a user already has the inventory grid open, should the shop grid show below the inventory grid? Sorry for all these questions, but I was wondering what your intention with the shop should be for it to work,.

All good, its good to ask my code is a mess anyway. When they type `shop` it should set the shopGrid.Visible to true which is dataGridView above the Stats GUI and is hidden by default. It will randomly populate the shop each time the game is started so even if there is a game save that's loaded (not implemented yet) it will generate new items in the shop randomly. About selling items I have not thought of but now that you mention it, should probably be added but I think its best to focus on buying first and fixing it. It updates the shop aka the grid every time the player opens it using `shop` so that the newly generated items can be added to the grid. It is also supposed to be used when an item is bought so the quantity of the item can be updated.

Yes it should I explained it just above.

**Comment by ohinson01** [comment]
Something like this? 
<img width="374" alt="image" src="https://github.com/ThatFrostyy/Survival/assets/69820358/3be87e2e-5aba-4387-8944-731e9766f060">

**Comment by ThatFrostyy** [comment]
> Something like this? <img alt="image" width="374" src="https://private-user-images.githubusercontent.com/69820358/309494663-3be87e2e-5aba-4387-8944-731e9766f060.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0MDYyNjcsIm5iZiI6MTcwOTQwNTk2NywicGF0aCI6Ii82OTgyMDM1OC8zMDk0OTQ2NjMtM2JlODdlMmUtNWFiYS00Mzg3LTg5NDQtNzMxZTk3NjZmMDYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAyVDE4NTkyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1MTgyODk3Njk1MWQ1Y2ZiNWEzOGM5YWRlYTFkZGVhZDQzM2UxZjEzOWFiZWRmNmY4YWM0YzZlNDBjNGFiZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rGqhCiJXZg8JWwoXTS_yZeKXM_H4YJGturl0ygEYjT0">

Yep like that although original idea was to it overlap over the GUI while we are in the village but that might not be the wisest idea. You have any suggestions? If not it can stay like you did it.

**Comment by ohinson01** [comment]
I did a few test items in the shop and found it does provide a scrollbar if you have a lot of items in there. 
<img width="372" alt="image" src="https://github.com/ThatFrostyy/Survival/assets/69820358/2d79feaa-2679-486a-a464-b23d72fbe06c">

I think having it overlap the whole states GUI might not be a great idea. My thinking is that users should be able to see where they are, the current weight and max weight to determine what to buy and how much they can carry. 
<img width="395" alt="image" src="https://github.com/ThatFrostyy/Survival/assets/69820358/8e9d2962-5b65-4358-ad52-334617668ef2">

Just FYI, the reason why the shop wasn't appearing in the first place was due to this line of code in Form1.cs. 
<img width="536" alt="image" src="https://github.com/ThatFrostyy/Survival/assets/69820358/9c636c0c-e5fc-4b07-90d4-403a978135a6">
I think what ended up happening was that because the Visible property was set to false, it was overriding any changes to that property you made going down the line. Once I commented this piece of code out, it worked like usual.

**Comment by ThatFrostyy** [comment]
> I did a few test items in the shop and found it does provide a scrollbar if you have a lot of items in there. <img alt="image" width="372" src="https://private-user-images.githubusercontent.com/69820358/309497358-2d79feaa-2679-486a-a464-b23d72fbe06c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0MDk5NzEsIm5iZiI6MTcwOTQwOTY3MSwicGF0aCI6Ii82OTgyMDM1OC8zMDk0OTczNTgtMmQ3OWZlYWEtMjY3OS00ODZhLWE0NjQtYjIzZDcyZmJlMDZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAyVDIwMDExMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0Yzc3NjM1MjcyZGQ2ZTAwNWQ0MTE0MGE0YTU4N2QxMGRmMDM2MjNhZDYyODVmNGYwZWQ3OWY5Yjk0N2U5NGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MqAm9ffG6ZF0I_TVq1BrTj2vGwV9R7hyExdcoiZvJqI">
> 
> I think having it overlap the whole stats GUI might not be a great idea. My thinking is that users should be able to see where they are, the current weight and max weight to determine what to buy and how much they can carry. <img alt="image" width="395" src="https://private-user-images.githubusercontent.com/69820358/309497415-8e9d2962-5b65-4358-ad52-334617668ef2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0MDk5NzEsIm5iZiI6MTcwOTQwOTY3MSwicGF0aCI6Ii82OTgyMDM1OC8zMDk0OTc0MTUtOGU5ZDI5NjItNWI2NS00MzU4LWFkNTItMzM0NjE3NjY4ZWYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAyVDIwMDExMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxMzRmZmQ5MTNmNmFlNzUyY2RiN2Q3ZTM3YWQxZmY0MTM0YTUyZjg0NDJmNWMwMjg5NWYyNzcyNDFiN2I4NTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OgLv5iEPVgoXGKo_emdNZKRhg88iLiAx7oKhF0C0EN8">
> 
> Just FYI, the reason why the shop wasn't appearing in the first place was due to this line of code in Form1.cs. <img alt="image" width="536" src="https://private-user-images.githubusercontent.com/69820358/309497626-9c636c0c-e5fc-4b07-90d4-403a978135a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0MDk5NzEsIm5iZiI6MTcwOTQwOTY3MSwicGF0aCI6Ii82OTgyMDM1OC8zMDk0OTc2MjYtOWM2MzZjMGMtZTVmYy00YjA3LTkwZDQtNDAzYTk3ODEzNWE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAyVDIwMDExMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3YTI5ZjFkZmUzNjA4YzNhZjM3Y2UwMzE3YzlkNDc5ZGEzNjAzMTdhZWZhYmJmOTEwNWYxNjZhMjVlNjQyMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.f_Y7z2tGZWqKua5bPIYTSnIO0f0NguZi348k2Dn5AYc"> I think what ended up happening was that because the Visible property was set to false, it was overriding any changes to that property you made going down the line. Once I commented this piece of code out, it worked like usual.

Oh alright, yea I agree with you on the look and position of the shop GUI. Just a quick question becuse in the screenshot I see there is still the `shop` command in the input box, does it get submitted (remove) once you press enter and get into the shop? like the other commands do?

**Comment by ohinson01** [comment]
When entering the shop command, it does not get removed. It stays in the textbox. I am assuming it should be like all the other commands and be removed once you press enter.

**Comment by ThatFrostyy** [comment]
> When entering the shop command, it does not get removed. It stays in the textbox. I am assuming it should be like all the other commands and be removed once you press enter.

Yea it should. There is still a issue somewhere then I would assume but I'm not sure. It could probably be with the way UpdateShop is called and still something with the shop object. Or it could just be in the method itself or on the event handler of the tooltip in the shop.

We could do a band-aid solution to just clear it ourselves in the code after updating the shop. And then see if we have some issues later? not sure.

**Comment by ohinson01** [comment]
Going to look through the code some more to see how the other commands are removed. It might tell me the root cause, or it might just be a weird issue that is happening and a band-aid solution needs to be added. I will let you know what else I find out once I have looked through it.

**Comment by ohinson01** [comment]
Found the issue. When you enter shop, there isn't any output to tell the program to clear the textbox after. I added a bit of output to let the user know they entered the village's shop. 
<img width="370" alt="image" src="https://github.com/ThatFrostyy/Survival/assets/69820358/f2f53ff0-4a8c-4118-857e-3d3ceb93486d">

**Comment by ohinson01** [comment]
I could create another Output() method so I do not have to enter text and it would clear it, but thought it wouldn't be consistent with how the game is set up right now.

**Comment by ohinson01** [comment]
Does this cover the entire issue? Wanted to make sure before I submitted the code changes.

**Comment by ThatFrostyy** [comment]
Yep it does. Also just wanna ask, you just made the shop usable right? No
like logic for the loop of it or whatever like exiting,  buying, etc just
the pure fix?

**Comment by ohinson01** [comment]
Correct. You can now use shop. I did not do any kind of logic to buy, exit, etc. I just made it usable. 
Also, looks like you recently made changes so am a bit hesitant to submit yet since the changes could get overwritten. How would you like me to go about merging my changes?

**Comment by ThatFrostyy** [comment]
> Correct. You can now use shop. I did not do any kind of logic to buy, exit, etc. I just made it usable. Also, looks like you recently made changes so am a bit hesitant to submit yet since the changes could get overwritten. How would you like me to go about merging my changes?

To be fair I'm not sure how the merges work when someone else contributes, I'm pretty sure either me who accepts, selects what can be overwritten or its the submitter the one.

**Comment by ohinson01** [comment]
Ok. I think I will make a new branch and send the pull request that way. It shouldn't interfere with any recent code changes (I think) and you can pull whatever is necessary to the main branch. I think that is how it works, but never did it myself.

**Comment by ohinson01** [comment]
According to this article I found on Pull Requests
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests

**Comment by ThatFrostyy** [comment]
> Ok. I think I will make a new branch and send the pull request that way. It shouldn't interfere with any recent code changes (I think) and you can pull whatever is necessary to the main branch. I think that is how it works, but never did it myself.

I looked it up fast and you can do however you want, if you create a pull request from the fork I can cherry pick anything from it.

**Comment by ohinson01** [comment]
Ok. Then I will just send a pull request from the fork without making a separate branch.

**Comment by ThatFrostyy** [comment]
Alright thanks for the help and contribution, I appricate it! If you want we can stay in touch and work on more problems if they arise.

> Ok. Then I will just send a pull request from the fork without making a separate branch.

**Comment by ohinson01** [comment]
No worries! Sure, we can stay in touch and work on more problems. 
I think I did the pull request. Let me know if anything else needs to be done.
