### ISSUE TITLE
PlayerMethods null in ShopMethods

### ISSUE THREAD

**Issue by ThatFrostyy** [ThatFrostyy/Survival#9]
Whenever we call the method `Buy` or `Sell` we get a exception saying that PlayerMethods is null. 
![image](https://github.com/ThatFrostyy/Survival/assets/79075783/4a3243b7-7137-4d8b-8ab0-025166e3626f)

Buy method
https://github.com/ThatFrostyy/Survival/blob/a4fb93c6a79d158a6c1041f1299c434337238284/Shop.cs#L158

Sell method
https://github.com/ThatFrostyy/Survival/blob/a4fb93c6a79d158a6c1041f1299c434337238284/Shop.cs#L182-L196

**Comment by ohinson01** [comment]
Leaving this here as a reminder to look into issue

**Comment by ThatFrostyy** [comment]
> Leaving this here as a reminder to look into issue

Now it let me assign it. You were not participating in it looks like lol.

**Comment by ThatFrostyy** [comment]
Currently doing a huge code rework, fixing the mess lol so it might be fixed when I'm done but we will see.

**Comment by ThatFrostyy** [comment]
Well its fixed now lol.

**Comment by ThatFrostyy** [comment]
Was fixed with the bed238bb347f41a5ee2b71d280703dda96826111 commit.
